### PR TITLE
on cancel, lets send customer back to checkout - as customer is expecting

### PR DESCRIPTION
**Pull request by michaelhjulskov**

### CODE REVIEW

**Comment by michaelhjulskov** [comment]
another thing in this file: long tima ago I had some errors in my php error log. dont know if its been fixed in this version already. please let me know, thanks.

I made this change:

		function readBitcoinpaymentdetails($id_order)
		{
			$db = Db::getInstance();
			$result = $db->ExecuteS('SELECT * FROM `' . _DB_PREFIX_ . 'order_coinify` WHERE `id_order` = ' . intval($id_order) . ';');
			// CHANGED - there is a possible issue here - orig code was: return $result[0];
			return (isset($result[0]) && is_array($result[0]))? $result[0] : false;
		}

**Comment by koalalorenzo** [comment]
Thanks for sharing this! 👍 I guess it will make more sense to redirect the user to the checkout page.

If you want, feel free to update the PR so we can check it and test it! (or create a new PR for each point you have).

**Comment by michaelhjulskov** [comment]
more feedback: 

I dont like that orders are created with status "Bitcoin Payment Expired"
that is not a good way to treat this situation because:
- shop owner get an order in BO that he does not want to see
- customer is not able to go back to cart and continue the trade

I would rather do like this:
at timeout just fire a javascript 
if confirm('timed out - please try again'){redirect customer back to the checkout}

**Comment by michaelhjulskov** [comment]
more feedback: on the coinify payment form there is no way to cancel. there should be and it should send customer back to cancel_url

**Pull request merged**
